Traceback (most recent call last):
  File "/home/pi/smsgway/sms-service.py", line 71, in <module>
    modem.sendSMS('081281012260', 'Sms Gway On')
  File "/home/pi/smsgway/sim800.py", line 109, in sendSMS
    wait_ok(15)
  File "/home/pi/smsgway/sim800.py", line 18, in wait_ok
    response =  ser.readline()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
